# Generated by Django 4.2.7 on 2023-11-29 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aud_app', '0002_alter_customuser_age_alter_customuser_altphone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='varients',
            name='stock',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='varients',
            name='variation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
