# Generated by Django 4.2.7 on 2023-12-01 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aud_app', '0003_alter_varients_stock_alter_varients_variation'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='varients',
            name='code',
            field=models.IntegerField(null=True),
        ),
    ]
