# Generated by Django 4.2.7 on 2023-12-08 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aud_app', '0011_order_quantity'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='order',
            table='Order',
        ),
    ]
