# Generated by Django 4.2.7 on 2023-12-12 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aud_app', '0012_alter_order_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100)),
                ('discount_price', models.IntegerField()),
                ('starting_date', models.DateField()),
                ('ending_date', models.DateField()),
                ('count', models.IntegerField()),
            ],
        ),
    ]
