# Generated by Django 4.2.7 on 2023-12-19 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Aud_app', '0017_razor_pay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='razor_pay',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='razor_pay', to='Aud_app.order'),
        ),
    ]
