# Generated by Django 4.2.7 on 2023-12-20 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Aud_app', '0020_rename_discount_price_varients_actual_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='varients',
            old_name='actual_price',
            new_name='discount_price',
        ),
    ]
