# Generated by Django 4.2.7 on 2023-12-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aud_app', '0022_remove_order_coupon_order_coupon_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
